import * as z from "zod";

export const gallerySchema = z.object({
  id: z.string().optional(),
  name: z.string().min(2, "Name must be at least 2 characters").min(1, "Name is required"),
  password: z.string().optional(),
  status: z.string().optional().default("active"),
  business_id: z.string().min(1, "Business is required"),
  logo: z.string().optional(),
  site_logo: z.string().optional(),
  description: z.string().optional(),
  primary_color: z.string().optional(),
  secondary_color: z.string().optional(),
  accent_color: z.string().optional(),
  primary_font_color: z.string().optional(),
  secondary_font_color: z.string().optional(),
  accent_font_color: z.string().optional(),
  heading_text: z.string().optional(),
  subheading_text: z.string().optional(),
  age_verification_text: z.string().optional(),
  button_text: z.string().optional(),
  age_verification_enabled: z.boolean().optional().default(false),
  password_required: z.boolean().optional().default(false),
  currentTab: z.string().optional().default("basic"),
  page_title: z.string().optional(),
  favicon: z.string().optional(),
  instructions_enabled: z.boolean().optional().default(false),
  instructions_content: z.string().optional(),
  instructions_button_text: z.string().optional().default("Enter Site"),
  show_description: z.boolean().optional().default(true),
  header_display: z.enum(["text", "logo"]).default("text"),
  pwa_icon_192: z.string().optional(),
  pwa_icon_512: z.string().optional(),
  screenshot_desktop: z.string().optional(),
  screenshot_mobile: z.string().optional(),
});

export type GalleryFormValues = z.infer<typeof gallerySchema>;